apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dqx0-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_GIT_REPO_URL
    targetRevision: main
    path: k8s/apps/api
  destination:
    server: https://kubernetes.default.svc
    namespace: dqx0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
