apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dqx0-ingress
  namespace: dqx0
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hello.dqx0
    - app.dqx0
    - api.dqx0
    secretName: dqx0-local-tls
  rules:
  - host: hello.dqx0
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello
            port:
              number: 80
  - host: app.dqx0
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 80
  - host: api.dqx0
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8080
